/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedSiteRouteImport } from './routes/_authenticated/site'
import { Route as AuthenticatedReputacaoRouteImport } from './routes/_authenticated/reputacao'
import { Route as AuthenticatedProntuarioRouteImport } from './routes/_authenticated/prontuario'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConteudoRouteImport } from './routes/_authenticated/conteudo'
import { Route as AuthenticatedAnunciosRouteImport } from './routes/_authenticated/anuncios'
import { Route as AuthenticatedAnamneseRouteImport } from './routes/_authenticated/anamnese'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as SSlugAnamneseRouteImport } from './routes/s.$slug.anamnese'
import { Route as SSlugAgendarRouteImport } from './routes/s.$slug.agendar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiteRoute = AuthenticatedSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReputacaoRoute = AuthenticatedReputacaoRouteImport.update({
  id: '/reputacao',
  path: '/reputacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProntuarioRoute = AuthenticatedProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConteudoRoute = AuthenticatedConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnunciosRoute = AuthenticatedAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnamneseRoute = AuthenticatedAnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugAnamneseRoute = SSlugAnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugAgendarRoute = SSlugAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => SSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/anamnese': typeof AuthenticatedAnamneseRoute
  '/anuncios': typeof AuthenticatedAnunciosRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/reputacao': typeof AuthenticatedReputacaoRoute
  '/site': typeof AuthenticatedSiteRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/s/$slug/agendar': typeof SSlugAgendarRoute
  '/s/$slug/anamnese': typeof SSlugAnamneseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/anamnese': typeof AuthenticatedAnamneseRoute
  '/anuncios': typeof AuthenticatedAnunciosRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/reputacao': typeof AuthenticatedReputacaoRoute
  '/site': typeof AuthenticatedSiteRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/s/$slug/agendar': typeof SSlugAgendarRoute
  '/s/$slug/anamnese': typeof SSlugAnamneseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/anamnese': typeof AuthenticatedAnamneseRoute
  '/_authenticated/anuncios': typeof AuthenticatedAnunciosRoute
  '/_authenticated/conteudo': typeof AuthenticatedConteudoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/prontuario': typeof AuthenticatedProntuarioRoute
  '/_authenticated/reputacao': typeof AuthenticatedReputacaoRoute
  '/_authenticated/site': typeof AuthenticatedSiteRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/s/$slug/agendar': typeof SSlugAgendarRoute
  '/s/$slug/anamnese': typeof SSlugAnamneseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/precos'
    | '/sitemap.xml'
    | '/agenda'
    | '/anamnese'
    | '/anuncios'
    | '/conteudo'
    | '/dashboard'
    | '/email'
    | '/onboarding'
    | '/prontuario'
    | '/reputacao'
    | '/site'
    | '/unidades'
    | '/s/$slug'
    | '/s/$slug/agendar'
    | '/s/$slug/anamnese'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/precos'
    | '/sitemap.xml'
    | '/agenda'
    | '/anamnese'
    | '/anuncios'
    | '/conteudo'
    | '/dashboard'
    | '/email'
    | '/onboarding'
    | '/prontuario'
    | '/reputacao'
    | '/site'
    | '/unidades'
    | '/s/$slug'
    | '/s/$slug/agendar'
    | '/s/$slug/anamnese'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/precos'
    | '/sitemap.xml'
    | '/_authenticated/agenda'
    | '/_authenticated/anamnese'
    | '/_authenticated/anuncios'
    | '/_authenticated/conteudo'
    | '/_authenticated/dashboard'
    | '/_authenticated/email'
    | '/_authenticated/onboarding'
    | '/_authenticated/prontuario'
    | '/_authenticated/reputacao'
    | '/_authenticated/site'
    | '/_authenticated/unidades'
    | '/s/$slug'
    | '/s/$slug/agendar'
    | '/s/$slug/anamnese'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrecosRoute: typeof PrecosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SSlugRoute: typeof SSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site': {
      id: '/_authenticated/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof AuthenticatedSiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reputacao': {
      id: '/_authenticated/reputacao'
      path: '/reputacao'
      fullPath: '/reputacao'
      preLoaderRoute: typeof AuthenticatedReputacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prontuario': {
      id: '/_authenticated/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof AuthenticatedProntuarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudo': {
      id: '/_authenticated/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof AuthenticatedConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios': {
      id: '/_authenticated/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AuthenticatedAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anamnese': {
      id: '/_authenticated/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AuthenticatedAnamneseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug/anamnese': {
      id: '/s/$slug/anamnese'
      path: '/anamnese'
      fullPath: '/s/$slug/anamnese'
      preLoaderRoute: typeof SSlugAnamneseRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/agendar': {
      id: '/s/$slug/agendar'
      path: '/agendar'
      fullPath: '/s/$slug/agendar'
      preLoaderRoute: typeof SSlugAgendarRouteImport
      parentRoute: typeof SSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAnamneseRoute: typeof AuthenticatedAnamneseRoute
  AuthenticatedAnunciosRoute: typeof AuthenticatedAnunciosRoute
  AuthenticatedConteudoRoute: typeof AuthenticatedConteudoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProntuarioRoute: typeof AuthenticatedProntuarioRoute
  AuthenticatedReputacaoRoute: typeof AuthenticatedReputacaoRoute
  AuthenticatedSiteRoute: typeof AuthenticatedSiteRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAnamneseRoute: AuthenticatedAnamneseRoute,
  AuthenticatedAnunciosRoute: AuthenticatedAnunciosRoute,
  AuthenticatedConteudoRoute: AuthenticatedConteudoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProntuarioRoute: AuthenticatedProntuarioRoute,
  AuthenticatedReputacaoRoute: AuthenticatedReputacaoRoute,
  AuthenticatedSiteRoute: AuthenticatedSiteRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SSlugRouteChildren {
  SSlugAgendarRoute: typeof SSlugAgendarRoute
  SSlugAnamneseRoute: typeof SSlugAnamneseRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugAgendarRoute: SSlugAgendarRoute,
  SSlugAnamneseRoute: SSlugAnamneseRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrecosRoute: PrecosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SSlugRoute: SSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
