/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedWhatsappAgenteRouteImport } from './routes/_authenticated/whatsapp-agente'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedTributosRouteImport } from './routes/_authenticated/tributos'
import { Route as AuthenticatedTissRouteImport } from './routes/_authenticated/tiss'
import { Route as AuthenticatedTeleconsultaRouteImport } from './routes/_authenticated/teleconsulta'
import { Route as AuthenticatedSiteRouteImport } from './routes/_authenticated/site'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedReputacaoRouteImport } from './routes/_authenticated/reputacao'
import { Route as AuthenticatedRepassesRouteImport } from './routes/_authenticated/repasses'
import { Route as AuthenticatedRecepcaoRouteImport } from './routes/_authenticated/recepcao'
import { Route as AuthenticatedProntuarioRouteImport } from './routes/_authenticated/prontuario'
import { Route as AuthenticatedPrescricoesRouteImport } from './routes/_authenticated/prescricoes'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedPacientesRouteImport } from './routes/_authenticated/pacientes'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNpsRouteImport } from './routes/_authenticated/nps'
import { Route as AuthenticatedMaquininhasRouteImport } from './routes/_authenticated/maquininhas'
import { Route as AuthenticatedLembretesRouteImport } from './routes/_authenticated/lembretes'
import { Route as AuthenticatedJornadasRouteImport } from './routes/_authenticated/jornadas'
import { Route as AuthenticatedIndicacoesRouteImport } from './routes/_authenticated/indicacoes'
import { Route as AuthenticatedFiscalRouteImport } from './routes/_authenticated/fiscal'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConveniosRouteImport } from './routes/_authenticated/convenios'
import { Route as AuthenticatedConteudoRouteImport } from './routes/_authenticated/conteudo'
import { Route as AuthenticatedContadorRouteImport } from './routes/_authenticated/contador'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCallcenterRouteImport } from './routes/_authenticated/callcenter'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedAnunciosRouteImport } from './routes/_authenticated/anuncios'
import { Route as AuthenticatedAnamneseRouteImport } from './routes/_authenticated/anamnese'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as SSlugAnamneseRouteImport } from './routes/s.$slug.anamnese'
import { Route as SSlugAgendarRouteImport } from './routes/s.$slug.agendar'
import { Route as ApiPublicHooksRunAutomationsRouteImport } from './routes/api/public/hooks/run-automations'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappAgenteRoute =
  AuthenticatedWhatsappAgenteRouteImport.update({
    id: '/whatsapp-agente',
    path: '/whatsapp-agente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTributosRoute = AuthenticatedTributosRouteImport.update({
  id: '/tributos',
  path: '/tributos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTissRoute = AuthenticatedTissRouteImport.update({
  id: '/tiss',
  path: '/tiss',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeleconsultaRoute =
  AuthenticatedTeleconsultaRouteImport.update({
    id: '/teleconsulta',
    path: '/teleconsulta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteRoute = AuthenticatedSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReputacaoRoute = AuthenticatedReputacaoRouteImport.update({
  id: '/reputacao',
  path: '/reputacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepassesRoute = AuthenticatedRepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecepcaoRoute = AuthenticatedRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProntuarioRoute = AuthenticatedProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescricoesRoute =
  AuthenticatedPrescricoesRouteImport.update({
    id: '/prescricoes',
    path: '/prescricoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacientesRoute = AuthenticatedPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNpsRoute = AuthenticatedNpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaquininhasRoute =
  AuthenticatedMaquininhasRouteImport.update({
    id: '/maquininhas',
    path: '/maquininhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLembretesRoute = AuthenticatedLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJornadasRoute = AuthenticatedJornadasRouteImport.update({
  id: '/jornadas',
  path: '/jornadas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicacoesRoute = AuthenticatedIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFiscalRoute = AuthenticatedFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConveniosRoute = AuthenticatedConveniosRouteImport.update({
  id: '/convenios',
  path: '/convenios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConteudoRoute = AuthenticatedConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContadorRoute = AuthenticatedContadorRouteImport.update({
  id: '/contador',
  path: '/contador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallcenterRoute = AuthenticatedCallcenterRouteImport.update({
  id: '/callcenter',
  path: '/callcenter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnunciosRoute = AuthenticatedAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnamneseRoute = AuthenticatedAnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugAnamneseRoute = SSlugAnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugAgendarRoute = SSlugAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => SSlugRoute,
} as any)
const ApiPublicHooksRunAutomationsRoute =
  ApiPublicHooksRunAutomationsRouteImport.update({
    id: '/api/public/hooks/run-automations',
    path: '/api/public/hooks/run-automations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/anamnese': typeof AuthenticatedAnamneseRoute
  '/anuncios': typeof AuthenticatedAnunciosRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/bi': typeof AuthenticatedBiRoute
  '/callcenter': typeof AuthenticatedCallcenterRoute
  '/chat': typeof AuthenticatedChatRoute
  '/contador': typeof AuthenticatedContadorRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/convenios': typeof AuthenticatedConveniosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fiscal': typeof AuthenticatedFiscalRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/jornadas': typeof AuthenticatedJornadasRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/maquininhas': typeof AuthenticatedMaquininhasRoute
  '/nps': typeof AuthenticatedNpsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/prescricoes': typeof AuthenticatedPrescricoesRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/repasses': typeof AuthenticatedRepassesRoute
  '/reputacao': typeof AuthenticatedReputacaoRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/site': typeof AuthenticatedSiteRoute
  '/teleconsulta': typeof AuthenticatedTeleconsultaRoute
  '/tiss': typeof AuthenticatedTissRoute
  '/tributos': typeof AuthenticatedTributosRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/whatsapp-agente': typeof AuthenticatedWhatsappAgenteRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/s/$slug/agendar': typeof SSlugAgendarRoute
  '/s/$slug/anamnese': typeof SSlugAnamneseRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/anamnese': typeof AuthenticatedAnamneseRoute
  '/anuncios': typeof AuthenticatedAnunciosRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/bi': typeof AuthenticatedBiRoute
  '/callcenter': typeof AuthenticatedCallcenterRoute
  '/chat': typeof AuthenticatedChatRoute
  '/contador': typeof AuthenticatedContadorRoute
  '/conteudo': typeof AuthenticatedConteudoRoute
  '/convenios': typeof AuthenticatedConveniosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fiscal': typeof AuthenticatedFiscalRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/jornadas': typeof AuthenticatedJornadasRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/maquininhas': typeof AuthenticatedMaquininhasRoute
  '/nps': typeof AuthenticatedNpsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/prescricoes': typeof AuthenticatedPrescricoesRoute
  '/prontuario': typeof AuthenticatedProntuarioRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/repasses': typeof AuthenticatedRepassesRoute
  '/reputacao': typeof AuthenticatedReputacaoRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/site': typeof AuthenticatedSiteRoute
  '/teleconsulta': typeof AuthenticatedTeleconsultaRoute
  '/tiss': typeof AuthenticatedTissRoute
  '/tributos': typeof AuthenticatedTributosRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/whatsapp-agente': typeof AuthenticatedWhatsappAgenteRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/portal': typeof PortalIndexRoute
  '/s/$slug/agendar': typeof SSlugAgendarRoute
  '/s/$slug/anamnese': typeof SSlugAnamneseRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/anamnese': typeof AuthenticatedAnamneseRoute
  '/_authenticated/anuncios': typeof AuthenticatedAnunciosRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/bi': typeof AuthenticatedBiRoute
  '/_authenticated/callcenter': typeof AuthenticatedCallcenterRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/contador': typeof AuthenticatedContadorRoute
  '/_authenticated/conteudo': typeof AuthenticatedConteudoRoute
  '/_authenticated/convenios': typeof AuthenticatedConveniosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fiscal': typeof AuthenticatedFiscalRoute
  '/_authenticated/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/_authenticated/jornadas': typeof AuthenticatedJornadasRoute
  '/_authenticated/lembretes': typeof AuthenticatedLembretesRoute
  '/_authenticated/maquininhas': typeof AuthenticatedMaquininhasRoute
  '/_authenticated/nps': typeof AuthenticatedNpsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/pacientes': typeof AuthenticatedPacientesRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/prescricoes': typeof AuthenticatedPrescricoesRoute
  '/_authenticated/prontuario': typeof AuthenticatedProntuarioRoute
  '/_authenticated/recepcao': typeof AuthenticatedRecepcaoRoute
  '/_authenticated/repasses': typeof AuthenticatedRepassesRoute
  '/_authenticated/reputacao': typeof AuthenticatedReputacaoRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/site': typeof AuthenticatedSiteRoute
  '/_authenticated/teleconsulta': typeof AuthenticatedTeleconsultaRoute
  '/_authenticated/tiss': typeof AuthenticatedTissRoute
  '/_authenticated/tributos': typeof AuthenticatedTributosRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRoute
  '/_authenticated/whatsapp-agente': typeof AuthenticatedWhatsappAgenteRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/s/$slug/agendar': typeof SSlugAgendarRoute
  '/s/$slug/anamnese': typeof SSlugAnamneseRoute
  '/api/public/hooks/run-automations': typeof ApiPublicHooksRunAutomationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/precos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/agenda'
    | '/anamnese'
    | '/anuncios'
    | '/automacoes'
    | '/bi'
    | '/callcenter'
    | '/chat'
    | '/contador'
    | '/conteudo'
    | '/convenios'
    | '/dashboard'
    | '/email'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/indicacoes'
    | '/jornadas'
    | '/lembretes'
    | '/maquininhas'
    | '/nps'
    | '/onboarding'
    | '/orcamentos'
    | '/pacientes'
    | '/pagamentos'
    | '/planos'
    | '/prescricoes'
    | '/prontuario'
    | '/recepcao'
    | '/repasses'
    | '/reputacao'
    | '/setup'
    | '/site'
    | '/teleconsulta'
    | '/tiss'
    | '/tributos'
    | '/unidades'
    | '/whatsapp-agente'
    | '/s/$slug'
    | '/portal/'
    | '/s/$slug/agendar'
    | '/s/$slug/anamnese'
    | '/api/public/hooks/run-automations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/precos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/agenda'
    | '/anamnese'
    | '/anuncios'
    | '/automacoes'
    | '/bi'
    | '/callcenter'
    | '/chat'
    | '/contador'
    | '/conteudo'
    | '/convenios'
    | '/dashboard'
    | '/email'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/indicacoes'
    | '/jornadas'
    | '/lembretes'
    | '/maquininhas'
    | '/nps'
    | '/onboarding'
    | '/orcamentos'
    | '/pacientes'
    | '/pagamentos'
    | '/planos'
    | '/prescricoes'
    | '/prontuario'
    | '/recepcao'
    | '/repasses'
    | '/reputacao'
    | '/setup'
    | '/site'
    | '/teleconsulta'
    | '/tiss'
    | '/tributos'
    | '/unidades'
    | '/whatsapp-agente'
    | '/s/$slug'
    | '/portal'
    | '/s/$slug/agendar'
    | '/s/$slug/anamnese'
    | '/api/public/hooks/run-automations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/precos'
    | '/privacidade'
    | '/sitemap.xml'
    | '/_authenticated/agenda'
    | '/_authenticated/anamnese'
    | '/_authenticated/anuncios'
    | '/_authenticated/automacoes'
    | '/_authenticated/bi'
    | '/_authenticated/callcenter'
    | '/_authenticated/chat'
    | '/_authenticated/contador'
    | '/_authenticated/conteudo'
    | '/_authenticated/convenios'
    | '/_authenticated/dashboard'
    | '/_authenticated/email'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/fiscal'
    | '/_authenticated/indicacoes'
    | '/_authenticated/jornadas'
    | '/_authenticated/lembretes'
    | '/_authenticated/maquininhas'
    | '/_authenticated/nps'
    | '/_authenticated/onboarding'
    | '/_authenticated/orcamentos'
    | '/_authenticated/pacientes'
    | '/_authenticated/pagamentos'
    | '/_authenticated/planos'
    | '/_authenticated/prescricoes'
    | '/_authenticated/prontuario'
    | '/_authenticated/recepcao'
    | '/_authenticated/repasses'
    | '/_authenticated/reputacao'
    | '/_authenticated/setup'
    | '/_authenticated/site'
    | '/_authenticated/teleconsulta'
    | '/_authenticated/tiss'
    | '/_authenticated/tributos'
    | '/_authenticated/unidades'
    | '/_authenticated/whatsapp-agente'
    | '/s/$slug'
    | '/portal/'
    | '/s/$slug/agendar'
    | '/s/$slug/anamnese'
    | '/api/public/hooks/run-automations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
  ApiPublicHooksRunAutomationsRoute: typeof ApiPublicHooksRunAutomationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp-agente': {
      id: '/_authenticated/whatsapp-agente'
      path: '/whatsapp-agente'
      fullPath: '/whatsapp-agente'
      preLoaderRoute: typeof AuthenticatedWhatsappAgenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tributos': {
      id: '/_authenticated/tributos'
      path: '/tributos'
      fullPath: '/tributos'
      preLoaderRoute: typeof AuthenticatedTributosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tiss': {
      id: '/_authenticated/tiss'
      path: '/tiss'
      fullPath: '/tiss'
      preLoaderRoute: typeof AuthenticatedTissRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teleconsulta': {
      id: '/_authenticated/teleconsulta'
      path: '/teleconsulta'
      fullPath: '/teleconsulta'
      preLoaderRoute: typeof AuthenticatedTeleconsultaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site': {
      id: '/_authenticated/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof AuthenticatedSiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reputacao': {
      id: '/_authenticated/reputacao'
      path: '/reputacao'
      fullPath: '/reputacao'
      preLoaderRoute: typeof AuthenticatedReputacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repasses': {
      id: '/_authenticated/repasses'
      path: '/repasses'
      fullPath: '/repasses'
      preLoaderRoute: typeof AuthenticatedRepassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recepcao': {
      id: '/_authenticated/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof AuthenticatedRecepcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prontuario': {
      id: '/_authenticated/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof AuthenticatedProntuarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescricoes': {
      id: '/_authenticated/prescricoes'
      path: '/prescricoes'
      fullPath: '/prescricoes'
      preLoaderRoute: typeof AuthenticatedPrescricoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes': {
      id: '/_authenticated/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AuthenticatedPacientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nps': {
      id: '/_authenticated/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof AuthenticatedNpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maquininhas': {
      id: '/_authenticated/maquininhas'
      path: '/maquininhas'
      fullPath: '/maquininhas'
      preLoaderRoute: typeof AuthenticatedMaquininhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lembretes': {
      id: '/_authenticated/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof AuthenticatedLembretesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jornadas': {
      id: '/_authenticated/jornadas'
      path: '/jornadas'
      fullPath: '/jornadas'
      preLoaderRoute: typeof AuthenticatedJornadasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicacoes': {
      id: '/_authenticated/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AuthenticatedIndicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiscal': {
      id: '/_authenticated/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof AuthenticatedFiscalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/convenios': {
      id: '/_authenticated/convenios'
      path: '/convenios'
      fullPath: '/convenios'
      preLoaderRoute: typeof AuthenticatedConveniosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudo': {
      id: '/_authenticated/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof AuthenticatedConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contador': {
      id: '/_authenticated/contador'
      path: '/contador'
      fullPath: '/contador'
      preLoaderRoute: typeof AuthenticatedContadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/callcenter': {
      id: '/_authenticated/callcenter'
      path: '/callcenter'
      fullPath: '/callcenter'
      preLoaderRoute: typeof AuthenticatedCallcenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios': {
      id: '/_authenticated/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AuthenticatedAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anamnese': {
      id: '/_authenticated/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AuthenticatedAnamneseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug/anamnese': {
      id: '/s/$slug/anamnese'
      path: '/anamnese'
      fullPath: '/s/$slug/anamnese'
      preLoaderRoute: typeof SSlugAnamneseRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/agendar': {
      id: '/s/$slug/agendar'
      path: '/agendar'
      fullPath: '/s/$slug/agendar'
      preLoaderRoute: typeof SSlugAgendarRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/api/public/hooks/run-automations': {
      id: '/api/public/hooks/run-automations'
      path: '/api/public/hooks/run-automations'
      fullPath: '/api/public/hooks/run-automations'
      preLoaderRoute: typeof ApiPublicHooksRunAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAnamneseRoute: typeof AuthenticatedAnamneseRoute
  AuthenticatedAnunciosRoute: typeof AuthenticatedAnunciosRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedBiRoute: typeof AuthenticatedBiRoute
  AuthenticatedCallcenterRoute: typeof AuthenticatedCallcenterRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedContadorRoute: typeof AuthenticatedContadorRoute
  AuthenticatedConteudoRoute: typeof AuthenticatedConteudoRoute
  AuthenticatedConveniosRoute: typeof AuthenticatedConveniosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFiscalRoute: typeof AuthenticatedFiscalRoute
  AuthenticatedIndicacoesRoute: typeof AuthenticatedIndicacoesRoute
  AuthenticatedJornadasRoute: typeof AuthenticatedJornadasRoute
  AuthenticatedLembretesRoute: typeof AuthenticatedLembretesRoute
  AuthenticatedMaquininhasRoute: typeof AuthenticatedMaquininhasRoute
  AuthenticatedNpsRoute: typeof AuthenticatedNpsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPacientesRoute: typeof AuthenticatedPacientesRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPrescricoesRoute: typeof AuthenticatedPrescricoesRoute
  AuthenticatedProntuarioRoute: typeof AuthenticatedProntuarioRoute
  AuthenticatedRecepcaoRoute: typeof AuthenticatedRecepcaoRoute
  AuthenticatedRepassesRoute: typeof AuthenticatedRepassesRoute
  AuthenticatedReputacaoRoute: typeof AuthenticatedReputacaoRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSiteRoute: typeof AuthenticatedSiteRoute
  AuthenticatedTeleconsultaRoute: typeof AuthenticatedTeleconsultaRoute
  AuthenticatedTissRoute: typeof AuthenticatedTissRoute
  AuthenticatedTributosRoute: typeof AuthenticatedTributosRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRoute
  AuthenticatedWhatsappAgenteRoute: typeof AuthenticatedWhatsappAgenteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAnamneseRoute: AuthenticatedAnamneseRoute,
  AuthenticatedAnunciosRoute: AuthenticatedAnunciosRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedBiRoute: AuthenticatedBiRoute,
  AuthenticatedCallcenterRoute: AuthenticatedCallcenterRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedContadorRoute: AuthenticatedContadorRoute,
  AuthenticatedConteudoRoute: AuthenticatedConteudoRoute,
  AuthenticatedConveniosRoute: AuthenticatedConveniosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFiscalRoute: AuthenticatedFiscalRoute,
  AuthenticatedIndicacoesRoute: AuthenticatedIndicacoesRoute,
  AuthenticatedJornadasRoute: AuthenticatedJornadasRoute,
  AuthenticatedLembretesRoute: AuthenticatedLembretesRoute,
  AuthenticatedMaquininhasRoute: AuthenticatedMaquininhasRoute,
  AuthenticatedNpsRoute: AuthenticatedNpsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPacientesRoute: AuthenticatedPacientesRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPrescricoesRoute: AuthenticatedPrescricoesRoute,
  AuthenticatedProntuarioRoute: AuthenticatedProntuarioRoute,
  AuthenticatedRecepcaoRoute: AuthenticatedRecepcaoRoute,
  AuthenticatedRepassesRoute: AuthenticatedRepassesRoute,
  AuthenticatedReputacaoRoute: AuthenticatedReputacaoRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSiteRoute: AuthenticatedSiteRoute,
  AuthenticatedTeleconsultaRoute: AuthenticatedTeleconsultaRoute,
  AuthenticatedTissRoute: AuthenticatedTissRoute,
  AuthenticatedTributosRoute: AuthenticatedTributosRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRoute,
  AuthenticatedWhatsappAgenteRoute: AuthenticatedWhatsappAgenteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SSlugRouteChildren {
  SSlugAgendarRoute: typeof SSlugAgendarRoute
  SSlugAnamneseRoute: typeof SSlugAnamneseRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugAgendarRoute: SSlugAgendarRoute,
  SSlugAnamneseRoute: SSlugAnamneseRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SSlugRoute: SSlugRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
  ApiPublicHooksRunAutomationsRoute: ApiPublicHooksRunAutomationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
